//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoundGame
    {
        public int Id { get; set; }
        public int GameId { get; set; }
        public System.DateTime DateTime { get; set; }
        public int ResultNumber { get; set; }
        public int ReslutMoney { get; set; }
        public virtual Game Game { get; set; }
    }
}
